### ISSUE TITLE
i can´t see emojis in my app with nativescript and angular after to install. 

### ISSUE THREAD

**Issue by jovanymezura** [dzfweb/nativescript-emoji#1]
Hello, the issue with plugin is after install and use the tags as was show in the README. don`t crash my app, but not show any message error and i dont see emojis. i made clone your demo app for test , then when i run demo(use run ios in terminal),  response then is an error and is the next :  

 > Module '/demo.app/app/nativescript-emoji' not found for element 'nativescript-emoji:Emoji'.
           > Could not find module '/demo.app/app/nativescript-emoji'. Computed path '/demo.app/app/nativescript-emoji'.Jun 15 11:41:19  (UIKitApplication:org.nativescript.demo[0xf30a][84346]): Service exited due to signal: Segmentation fault: 11

Any kind of guidance on this topic would greatly appreciate it. Greetings and good work.

**Comment by dzfweb** [comment]
Hi @jovanymezura 
Could you please share your code ?
What emoji short name did you use?
See if it is a valid shortname at emoji database:
https://github.com/dzfweb/nativescript-emoji/blob/master/emoji.database.ts

To try the sample code you need to run the following command before, at the root of the plugin folder:
`npm run preparedemo`
`npm run demo.ios`
`npm run demo.android`

**Comment by jovanymezura** [comment]
oh hi, sure in my component i do import emoji as follows 

```
import { Emoji } from 'nativescript-emoji';
import { registerElement } from "nativescript-angular/element-registry";

registerElement("Emoji", () => require("nativescript-emoji").Emoji);
```

and that is all. 

in the file html. 
used this      
```
  <StackLayout orientation="horizontal"  row="7" col="1">
                <Label text="I'm happy "> </Label>
                <Emoji:Emoji name="joy" ></Emoji:Emoji>
            </StackLayout>
```

**Comment by dzfweb** [comment]
I couldn't reproduce the error you're getting.
I created a new nativescript angular test and it happened all right.

`tns create angulartest --ng`
`tns plugin add nativescript-emoji`

*app.module.ts*
```
import { registerElement } from "nativescript-angular/element-registry";
registerElement("Emoji", () => require("nativescript-emoji").Emoji);
```

*items.component.html*
```
<StackLayout orientation="horizontal"  row="7" col="1">
    <Label text="I'm happy "> </Label>
    <Emoji:Emoji name="joy" ></Emoji:Emoji>
</StackLayout>
```

result: http://imgur.com/a/GuX3k 

Please, let me know what tns version of your project, the plugin need at least 3.0 version

**Comment by jovanymezura** [comment]
You're right, I also did a new project to do tests and everything works fine. I can see the emojis, although in my app you can not do the installation again, waiting for that to fix the problem. I appreciate the quick help and send you good vibes.

**Comment by dzfweb** [comment]
The nativescript version in your app is lower than 3.0, right? Can you update it?

**Comment by jovanymezura** [comment]
i have this version  nativescript     │ 3.0.1

**Comment by dzfweb** [comment]
Close due to #2
