### ISSUE TITLE
sizes problems with Emojis

### ISSUE THREAD

**Issue by jovanymezura** [dzfweb/nativescript-emoji#2]
Hi, I've managed to put Emoji in my application. The problem I now have is that I could not change the size of the emojis, I attach the snippet that I use. And although I put a size value I do not see size changes for emojis.

`<Emoji:Emoji name="{{item.name}}" size="100"/>`

I have also tried a cloned project of your demo and I did not get to see the size change of the emojis, could you guide me to perform this task?

this is the snippet: 

```
`<ActionBar title="EmojiMx">
</ActionBar>
<StackLayout orientation="horizontal" >
    <Label text="I'm happy QQ"></Label>
    <Emoji:Emoji name="joy" size="100" />
    <Emoji:Emoji name="joy"  size="50"/>
    <Emoji:Emoji name="joy" size="10"/>
</StackLayout>`
```

“Best regards”

Apparently the issue is only in IOS. in Android if change size emojis

**Comment by dzfweb** [comment]
Hi @jovanymezura,
please let me know the version of nativescript-emoji you are using.
The size property was released on 1.1.1 version.

**Comment by jovanymezura** [comment]
"nativescript-emoji": "^1.1.1", version AND Apparently the issue is only in IOS. in Android if change size emojis.

**Comment by dzfweb** [comment]
I tried and i'm able to change the emoji's size.

Android:
![screenshot_175](https://user-images.githubusercontent.com/10212321/27357180-9138bc94-55e7-11e7-9680-a8ff8f3fa3f3.png)

iOS: 
![screenshot_176](https://user-images.githubusercontent.com/10212321/27357202-a3d34c02-55e7-11e7-9063-53c7ff299c44.png)

I don't know if the iOS version is influencing, i dont think so.

**Comment by jovanymezura** [comment]
it was tested in simulator 10.3(IOS)  and Xcode 7.0 version.
and IOS 10.3.2 in device. 
and simulator 10.3 (xcode 8.3).

I do not know what is happening. 
Thanks for a quick reply
