### ISSUE TITLE
Emoji names list

### ISSUE THREAD

**Issue by OPADA-Eng** [dzfweb/nativescript-emoji#3]
Thanks for great plugin, but I'm wondering where to find a full list of the emoji list ?

**Comment by dzfweb** [comment]
Hi @OPADA-Eng 

you can view the full list of emoji at our emoji-database:

https://raw.githubusercontent.com/dzfweb/nativescript-emoji/master/emoji.database.ts

use the "shortname" value.

**Comment by OPADA-Eng** [comment]
Thanks.

On Aug 2, 2017 7:55 PM, "Douglas Franco" <notifications@github.com> wrote:

Hi @OPADA-Eng <https://github.com/opada-eng>

you can view the full list of emoji at our emoji-database:

https://raw.githubusercontent.com/dzfweb/nativescript-emoji/
master/emoji.database.ts

use the "shortname" value.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dzfweb/nativescript-emoji/issues/3#issuecomment-319733080>,
or mute the thread
